bash transformers_summarization.sh -i /projects/oleksandry/privacy-data/anonymized_flair/summarization_wiki/cnndm_train.csv -v /projects/oleksandry/privacy-data/anonymized_flair/summarization_wiki/cnndm_val.csv -t /projects/oleksandry/privacy-data/anonymized_flair/summarization_wiki/cnndm_test.csv -x flair_wiki
#bash transformers_summarization.sh -i /projects/oleksandry/privacy-data/anonymized_flair/summarization_placeholder/cnndm_train.csv -v /projects/oleksandry/privacy-data/anonymized_flair/summarization_placeholder/cnndm_val.csv -t /projects/oleksandry/privacy-data/anonymized_flair/summarization_placeholder/cnndm_test.csv -x flair_placeholder
bash transformers_summarization.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/summarization_wiki/cnndm_train.csv -v /projects/oleksandry/privacy-data/anonymized_spacy/summarization_wiki/cnndm_val.csv -t /projects/oleksandry/privacy-data/anonymized_spacy/summarization_wiki/cnndm_test.csv -x spacy_wiki
bash transformers_summarization.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/summarization_placeholder/cnndm_train.csv -v /projects/oleksandry/privacy-data/anonymized_spacy/summarization_placeholder/cnndm_val.csv -t /projects/oleksandry/privacy-data/anonymized_spacy/summarization_placeholder/cnndm_test.csv -x spacy_placeholder
bash transformers_summarization.sh -i /projects/oleksandry/privacy-data/original_data/cnn_dm/train.json -v /projects/oleksandry/privacy-data/original_data/cnn_dm/val.json -t /projects/oleksandry/privacy-data/original_data/cnn_dm/test.json -x original

bash classification.sh -i /projects/oleksandry/privacy-data/anonymized_flair/classification_placeholder/imdb_train.csv -t /projects/oleksandry/privacy-data/anonymized_flair/classification_placeholder/imdb_test.csv -x flair_placeholder
bash classification.sh -i /projects/oleksandry/privacy-data/anonymized_flair/classification_wiki/imdb_train.csv -t /projects/oleksandry/privacy-data/anonymized_flair/classification_wiki/imdb_test.csv -x flair_wiki
bash classification.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/classification_placeholder/imdb_train.csv -t /projects/oleksandry/privacy-data/anonymized_spacy/classification_placeholder/imdb_test.csv -x spacy_placeholder
bash classification.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/classification_wiki/imdb_train.csv -t /projects/oleksandry/privacy-data/anonymized_spacy/classification_wiki/imdb_test.csv -spacy_wiki
bash classification.sh -i /projects/oleksandry/privacy-data/original_data/classification/imdb_train.csv -t /projects/oleksandry/privacy-data/original_data/classification/imdb_test.csv -x original


#bash transformers_translation.sh -i /projects/oleksandry/privacy-data/anonymized_flair/translation_wiki/wmt15_en_de_train.csv.json -t /projects/oleksandry/privacy-data/anonymized_flair/translation_wiki/wmt15_en_de_test.csv.json -x flair_wiki
bash transformers_translation.sh -i /projects/oleksandry/privacy-data/anonymized_flair/translation_placeholder/wmt15_en_de_train.csv -t /projects/oleksandry/privacy-data/anonymized_flair/translation_placeholder/wmt15_en_de_test.csv -x flair_placeholder
#bash transformers_translation.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/translation_wiki/wmt15_en_de_train.csv.json -t /projects/oleksandry/privacy-data/anonymized_spacy/translation_wiki/wmt15_en_de_test.csv.json -x spacy_wiki
bash transformers_translation.sh -i /projects/oleksandry/privacy-data/anonymized_spacy/translation_placeholder/wmt15_en_de_train.csv -t /projects/oleksandry/privacy-data/anonymized_spacy/translation_placeholder/wmt15_en_de_test.csv -x spacy_placeholder
bash transformers_translation.sh -i /projects/oleksandry/privacy-data/original_data/wmt2015/train.json -t /projects/oleksandry/privacy-data/original_data/wmt2015/newstest2015.json -x original
